### ISSUE TITLE
Loading error popup

### ISSUE THREAD

**Issue by qtweeder** [hotrodman106/XMR-Stak-Hashrate-Viewer#1]
**Describe the bug**
when opening file, get an error popup

**Screenshots**
![Image1](https://user-images.githubusercontent.com/49302192/56383565-012a6600-6212-11e9-801b-eb2e66be5162.jpg)

**Desktop (please complete the following information):**
 - OS: windows 10 64 1809
 - Program Version: v3.0

**Comment by hotrodman106** [comment]
Current executable pulled. Forgot to add reference to assembly during build. Please keep an eye out for the updated release

**Comment by qtweeder** [comment]
do you need me to remove that image with the public key token in?

**Comment by hotrodman106** [comment]
> do you need me to remove that image with the public key token in?

Nope

**Comment by qtweeder** [comment]
works great, nice extra info, thanks for the fix!
